# Generated by Django 4.0.4 on 2022-04-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='core.tag')),
            ],
        ),
    ]
